COLUMNS_TO_STAY = [
    'IP',
    'totalPerDevice',
    'ipAvgMinutesActive',
    'ipMinutesActivePerDay50',
    'ipMinutesActivePerDay90',
    'ipMinutesActivePerDay99',
    'deviceIdMinMinutesActive',
    'deviceIdAvgMinutesActive',
    'deviceIdMinutesActivePerDay50',
    'deviceIdMinutesActivePerDay90',
    'deviceIdMinutesActivePerDay99',
    'b3',
    'ttlQ50',
    'ttlQ99',
    'xDeviceUaImpressionRatio',
    'ipMismatchRatio',
    'noKv4InXffRatio',
    'nullDeviceIdRatio',
    'minAppsPerDevice',
    'maxAppsPerDevice',
    'avgAppsPerDevice',
    'totalAppsQ50',
    'totalAppsQ90',
    'totalAppsQ99',
]

CREDENTIALS_PATH = 'src/credentials/google_compute_engine_prd.json'
